### ISSUE TITLE
Get Institution Login Form endpoint not working

### ISSUE THREAD

**Issue by mpherman1** [finapps/python-client#1]
I am getting a 404 error when I attempt to access the "get institution form" endpoint. The documentation says that the endpoint is "GET /v2/institutions/:site_id/form". I used the institution search endpoint to find site ID 6647, and also tried site ID 16441/. Neither work. You can find the tests in the restructure branch under api_tests/get_institution_form_test.py

**Comment by george-fa** [comment]
{{url}}/v2/institutions/site/16441/form

Was the current endpoint and param - developer docs are out of date.
